# Build a .Net Framework Solution for a web project
# If it's the main branch publish for release

## Usage
### ```yml
### resources:
###   repositories:
###   - repository: AdoCommonTools
###     name: Software/AdoCommonTools
###     type: git
###     ref: main
###
### stages:
###   - stage: BuildAndTest
###     jobs:
###     - template: Pipelines/Framework/frameworkBuildAndTest.yml@AdoCommonTools
###       parameters:
###         buildConfiguration: ${{ variables.buildConfiguration }}
###         solution: ${{ variables.solution }}
###         artifactName: ${{ variables.name }}
### ```

parameters:
  - name: buildConfiguration
    type: string
    default: "Release"
    values:
      - Debug
      - Test
      - Release
  - name: solution
    type: string
  - name: artifactName
    type: string
  - name: buildPlatform
    type: string
    default: "Any CPU"
  - name: isMain
    type: string
    values:
      - "true"
      - "false"

jobs:
  - job: BuildAndTest
    displayName: "Build and Test"
    steps:
      - task: NuGetToolInstaller@1
        displayName: "Nuget Install"

      - task: NuGetCommand@2
        displayName: "Nuget Restore"
        inputs:
          restoreSolution: ${{ parameters.solution }}

      - task: VSBuild@1
        displayName: "Build Solution (.NET Framework)"
        # only run on PR builds to ensure it builds
        condition: ${{ ne(parameters.isMain, 'true') }}
        inputs:
          solution: "${{ parameters.solution }}"
          platform: ${{ parameters.buildPlatform }}
          configuration: ${{ parameters.buildConfiguration }}

      # The web.config is transformed based on the parameters.buildConfiguration with the /p:TransformConfigFile=true arg
      # see the Readme.md for more details
      - task: VSBuild@1
        displayName: "DEV - Build And Publish Solution (.NET Framework) on Main"
        condition: ${{ eq(parameters.isMain, 'true') }}
        inputs:
          solution: ${{ parameters.solution }}
          msbuildArgs: '/p:PackageLocation="$(Build.ArtifactStagingDirectory)/Dev" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:TransformConfigFile=true'
          platform: ${{ parameters.buildPlatform }}
          configuration: "Debug"

      - task: VSBuild@1
        displayName: "PROD - Build And Publish Solution (.NET Framework) on Main"
        condition: ${{ eq(parameters.isMain, 'true') }}
        inputs:
          solution: ${{ parameters.solution }}
          msbuildArgs: '/p:PackageLocation="$(Build.ArtifactStagingDirectory)/Prod" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:TransformConfigFile=true'
          platform: ${{ parameters.buildPlatform }}
          configuration: "Release"

      - task: VSTest@3
        displayName: "Run Tests"
        inputs:
          platform: ${{ parameters.buildPlatform }}
          configuration: ${{ parameters.buildConfiguration }}
          # this publishes the codecoverage to the pipeline results
          codeCoverageEnabled: True

      - task: PublishBuildArtifacts@1
        displayName: "DEV - Publish Build Artifacts"
        condition: ${{ eq(parameters.isMain, 'true') }}
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Dev"
          artifactName: "${{ parameters.artifactName }}_Dev"

      - task: PublishBuildArtifacts@1
        displayName: "PROD - Publish Build Artifacts"
        condition: ${{ eq(parameters.isMain, 'true') }}
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Prod"
          artifactName: "${{ parameters.artifactName }}_Prod"
