# Build .Net Web apps with artifacts for deployment
# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=yaml-editor
# these can run on ubuntu-latest

parameters:
  - name: netVersion
    type: string
    default: "8.x"
  - name: buildConfiguration
    type: string
    default: "Release"
  - name: rootFolder
    type: string
  - name: artifactName
    type: string
  - name: isMain
    type: string
    values:
      - "true"
      - "false"
  # IIS does not run with single file "Common solutions to this issue: The app couldn't be found. Confirm the app's main DLL is present. Single-file deployments are not supported in IIS."      
  - name: publishSingleFile
    type: string
    default: "true"
    values:
      - "true"
      - "false"

jobs:
  - job: BuildAndTest
    displayName: "Build and Test"
    steps:
      - task: UseDotNet@2
        displayName: "Install .NET SDK"
        inputs:
          version: ${{ parameters.netVersion }}
          performMultiLevelLookup: true
          includePreviewVersions: true

      - task: NuGetAuthenticate@1
        displayName: "NuGet Authenticate"

      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: "restore"
          projects: "${{ parameters.rootFolder }}/**/*.csproj"
          feedsToUse: "config"
          # Nuget.config should be at the root of the repo
          nugetConfigPath: "NuGet.config"

      - task: DotNetCoreCLI@2
        displayName: "Build With ${{ parameters.buildConfiguration }} Configuration"
        inputs:
          command: build
          projects: "${{ parameters.rootFolder }}/**/*.csproj"
          arguments: "--configuration ${{ parameters.buildConfiguration }}"

      # on Linux, use Coverlet
      - task: DotNetCoreCLI@2
        displayName: "Test"
        inputs:
          command: "test"
          projects: "${{ parameters.rootFolder }}/**/*Tests.csproj"
          arguments: '--configuration Debug --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
          publishTestResults: true

      - task: PublishCodeCoverageResults@2
        displayName: "Publish code coverage report"
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(Agent.TempDirectory)/**/coverage.cobertura.xml"

      # /p:EnvironmentName=Development or Staging adds and sets the ASPNETCORE_ENVIRONMENT to the web.config
      - task: DotNetCoreCLI@2
        condition: and(succeeded(), ${{ eq(parameters.isMain, 'true') }})
        displayName: "Publish Development"
        inputs:
          command: publish
          projects: |
            ${{ parameters.rootFolder }}/**/*.csproj
            !${{ parameters.rootFolder }}/**/*Tests.csproj
          publishWebProjects: false
          publishTestResults: false
          ${{ if eq(parameters.publishSingleFile, 'true') }}:
            arguments: "--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/Dev /p:EnvironmentName=Development -p:PublishSingleFile=true --self-contained --runtime win-x64 /p:IncludeNativeLibrariesForSelfExtract=true"
          ${{ else }}:
            arguments: "--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/Dev /p:EnvironmentName=Development"
          zipAfterPublish: false
          # use false, the output is placed directly in the specified output directory.
          modifyOutputPath: false

      - task: PowerShell@2
        displayName: "Remove unwanted appsettings and create ${{parameters.artifactName}} zip for Dev"
        condition: and(succeeded(), ${{ eq(parameters.isMain, 'true') }})
        inputs:
          targetType: "inline"
          script: |
            $src = "$(Build.ArtifactStagingDirectory)/Dev"

            Write-Host "Cleaning unwanted appsettings from $src"
            $remove = @('appsettings.Production.json','appsettings.Test.json')
            foreach ($f in $remove) {
              Get-ChildItem -Path $src -Filter $f -Recurse -File -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
            }

            $zipPath = "$(Build.ArtifactStagingDirectory)/Dev/${{parameters.artifactName}}.zip"
            Write-Host "Creating zip: $zipPath"
            Compress-Archive -Path $src\* -DestinationPath $zipPath -Force

      - task: DotNetCoreCLI@2
        condition: and(succeeded(), ${{ eq(parameters.isMain, 'true') }})
        displayName: "Publish Production"
        inputs:
          command: publish
          projects: |
            ${{ parameters.rootFolder }}/**/*.csproj
            !${{ parameters.rootFolder }}/**/*Tests.csproj
          publishWebProjects: false
          publishTestResults: false
          ${{ if eq(parameters.publishSingleFile, 'true') }}:
            arguments: "--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/Prod /p:EnvironmentName=Production -p:PublishSingleFile=true --self-contained --runtime win-x64 /p:IncludeNativeLibrariesForSelfExtract=true"
          ${{ else }}:
            arguments: "--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/Prod /p:EnvironmentName=Production"
          zipAfterPublish: false
          modifyOutputPath: false

      - task: PowerShell@2
        displayName: "Remove unwanted appsettings and create ${{parameters.artifactName}} zip for Prod"
        condition: and(succeeded(), ${{ eq(parameters.isMain, 'true') }})
        inputs:
          targetType: "inline"
          script: |
            $src = "$(Build.ArtifactStagingDirectory)/Prod"

            Write-Host "Cleaning unwanted appsettings from $src"
            $remove = @('appsettings.Development.json','appsettings.Test.json')
            foreach ($f in $remove) {
              Get-ChildItem -Path $src -Filter $f -Recurse -File -ErrorAction SilentlyContinue | Remove-Item -Force -ErrorAction SilentlyContinue
            }

            $zipPath = "$(Build.ArtifactStagingDirectory)/Prod/${{parameters.artifactName}}.zip"
            Write-Host "Creating zip: $zipPath"
            Compress-Archive -Path $src\* -DestinationPath $zipPath -Force

      - task: PublishBuildArtifacts@1
        displayName: "DEV - Publish Build Artifacts"
        condition: and(succeeded(), ${{ eq(parameters.isMain, 'true') }})
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Dev/${{parameters.artifactName}}.zip"
          artifactName: "${{ parameters.artifactName }}_Dev"

      - task: PublishBuildArtifacts@1
        displayName: "PROD - Publish Build Artifacts"
        condition: and(succeeded(), ${{ eq(parameters.isMain, 'true') }})
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/Prod/${{parameters.artifactName}}.zip"
          artifactName: "${{ parameters.artifactName }}_Prod"
