# Build .Net Web apps with artifacts for deployment
# https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=yaml-editor
# these can run on ubuntu-latest

parameters:
  - name: netVersion
    type: string
    default: "10.x"
  - name: buildConfiguration
    type: string
    default: "Release"
  - name: rootFolder
    type: string
  # The folder of the main/Program.cs project, added later
  - name: publishAppFolder
    type: string
    default: ""
  - name: artifactName
    type: string
  - name: isMain
    type: string
    values:
      - "true"
      - "false"
  # IIS does not run with single file "Common solutions to this issue: The app couldn't be found. Confirm the app's main DLL is present. Single-file deployments are not supported in IIS."      
  - name: publishSingleFile
    type: string
    default: "true"
    values:
      - "true"
      - "false"
  # build artifacts for the given environments
  - name: environmentNames
    type: string
    default: "POC, TST, REL, PRD"
  # new testing mode is the Microsoft Testing Platform: https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test
  # this is designated in the global.json
  - name: mtp
    type: string
    default: "false"
    values:
      - "true"
      - "false"

jobs:
  - job: BuildAndTest
    displayName: "Build, Test and Publish"
    steps:
      - task: UseDotNet@2
        displayName: "Install .NET SDK"
        inputs:
          version: ${{ parameters.netVersion }}
          performMultiLevelLookup: true
          includePreviewVersions: true
          
      - task: NuGetAuthenticate@1
        displayName: "NuGet Authenticate"
      
      - task: DotNetCoreCLI@2
        displayName: "Restore"
        inputs:
          command: "restore"
          projects: "${{ parameters.publishAppFolder }}/**/*.csproj"
          feedsToUse: "config"
          # Nuget.config should be at the root of the repo
          nugetConfigPath: 'NuGet.config'

      - task: DotNetCoreCLI@2
        displayName: 'Build With ${{ parameters.buildConfiguration }} Configuration'
        inputs:
          command: build
          projects: '${{ parameters.publishAppFolder }}/**/*.csproj'
          arguments: '--configuration ${{ parameters.buildConfiguration }}'

      - ${{ if eq(parameters.mtp, 'true') }}:
        - task: DotNetCoreCLI@2
          displayName: 'Run tests and collect coverage (MTP)'
          inputs:
            command: test
            projects: '${{ parameters.rootFolder }}/*Tests/*.csproj'
            # need Microsoft.Testing.Extensions.TrxReport for Trx
            # need Microsoft.Testing.Extensions.CodeCoverag for -Coverage
            # Consider adding --report-gh in GitHub Actions or dotnet test --report-azdo in Azure DevOps. https://devblogs.microsoft.com/dotnet/microsoft-testing-platform-reporting/
            # a testconfig.json could be helpful in the project and less configuration here
            arguments: >
              --configuration ${{ parameters.buildConfiguration }}
              --report-trx
              --coverage
              --coverage-output-format cobertura

      - ${{ if ne(parameters.mtp, 'true') }}:
        - task: DotNetCoreCLI@2
          displayName: 'Run tests and collect coverage (XPlat/VSTest)'
          inputs:
            command: test
            projects: '**/*Tests/*.csproj'
            arguments: >
              --configuration ${{ parameters.buildConfiguration }}
              --logger trx
              --collect:"XPlat Code Coverage"
              --DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      - task: PublishCodeCoverageResults@2
        displayName: 'Publish Code Coverage'
        inputs:
          summaryFileLocation: '$(Agent.TempDirectory)/**/*.cobertura.xml'
          failIfCoverageEmpty: false

      - ${{ if and(eq(parameters.isMain, 'true'), contains(parameters.environmentNames, 'POC')) }}:
          - template: netBuildAndTest_BuildCleanPublish.yml
            parameters:
              environmentName: 'POC'
              artifactName: ${{ parameters.artifactName }}
              publishAppFolder: ${{ parameters.publishAppFolder }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              publishSingleFile: ${{ parameters.publishSingleFile }}
              removeAppSettings: 'appsettings.Local.json|appsettings.PRD.json|appsettings.REL.json|appsettings.TST.json'

      - ${{ if and(eq(parameters.isMain, 'true'), contains(parameters.environmentNames, 'TST')) }}:
          - template: netBuildAndTest_BuildCleanPublish.yml
            parameters:
              environmentName: 'TST'
              artifactName: ${{ parameters.artifactName }}
              publishAppFolder: ${{ parameters.publishAppFolder }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              publishSingleFile: ${{ parameters.publishSingleFile }}
              removeAppSettings: 'appsettings.Local.json|appsettings.PRD.json|appsettings.REL.json|appsettings.POC.json'

      - ${{ if and(eq(parameters.isMain, 'true'), contains(parameters.environmentNames, 'REL')) }}:
          - template: netBuildAndTest_BuildCleanPublish.yml
            parameters:
              environmentName: 'REL'
              artifactName: ${{ parameters.artifactName }}
              publishAppFolder: ${{ parameters.publishAppFolder }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              publishSingleFile: ${{ parameters.publishSingleFile }}
              removeAppSettings: 'appsettings.Local.json|appsettings.PRD.json|appsettings.TST.json|appsettings.POC.json'

      - ${{ if and(eq(parameters.isMain, 'true'), contains(parameters.environmentNames, 'PRD')) }}:
          - template: netBuildAndTest_BuildCleanPublish.yml
            parameters:
              environmentName: 'PRD'
              artifactName: ${{ parameters.artifactName }}
              publishAppFolder: ${{ parameters.publishAppFolder }}
              buildConfiguration: ${{ parameters.buildConfiguration }}
              publishSingleFile: ${{ parameters.publishSingleFile }}
              removeAppSettings: 'appsettings.Local.json|appsettings.REL.json|appsettings.TST.json|appsettings.POC.json'
